### ISSUE TITLE
This demo is not working.

### ISSUE THREAD

**Issue by Pinturaj** [suxinde2009/TouchIDKit#1]
No such module 'TouchIDKit'
is available.

**Comment by 0xFA709394** [comment]
@Pinturaj 
I just checked a few minutes ago, it works fine for me.
Were your running the demo on the target 'TouchIDKitDemo' ?
Clean and try to build again, if that doesn't work, I suppose you could create a new project, integrate this framework with cococapods. 
 Cococapods can help you get rid of the XCode configuration stuffs of library dependency.

**Comment by 0xFA709394** [comment]
No further information, closed.
